### ISSUE TITLE
Very high CPU load when  AsyncMQTT-SN Gateway starting

### ISSUE THREAD

**Issue by ngocphu811** [ty4tw/AsyncMQTT-SN#1]
When start AsyncMQTT-SN Gateway, the CPU load was too high ( ~ 100%).
Anyone has faced this issue?

**Comment by ty4tw** [comment]
%CPU on my laptop is 38%.  I changed TIMEOUT_PERIOD 10millseconds to 10 secs.
Then CPU load is now 24%.

**Comment by ngocphu811** [comment]
Thank Tomoaki,
I have tried to change TIMEOUT_PERIOD to 10 secs.And the CPU load is now down to below 50%.But I wonder that whether this change effects to the Gateway  functionality?

**Comment by ty4tw** [comment]
Do not worry.  Program logic is event driven, not polling.
10 secs time out of the event queue is to check the other threads terminated. 
if terminated, GatewayControlTask should stop.
