### ISSUE TITLE
How to stop TomyGateway

### ISSUE THREAD

**Issue by zwgraham** [ty4tw/AsyncMQTT-SN#2]
Hi Tomy,

What is the proper way to shut down TomyGateway? CTL-C doesn't work, I usually kill it in a separate terminal.

**Comment by ty4tw** [comment]
Hi,
Since it is assumed that runs as a service, it ignores the CTL-C.
Pls, kill it in separate terminal.

**Comment by ty4tw** [comment]
I have uploaded a candidate gateway for Paho to https://github.com/ty4tw/paho.mqtt-sn.embedded-c.git
This gateway can be stopped by CTL-C.
